### ISSUE TITLE
ModuleNotFoundError: No module named 'zope

### ISSUE THREAD

**Issue by erifre** [flathub/org.deluge_torrent.deluge#18]
In the latest published version you can no longer run Deluge in daemon mode. When you do it complains about a missing module.

The version before works fine.

```
Traceback (most recent call last):
  File "/app/bin/deluged", line 33, in <module>
    sys.exit(load_entry_point('deluge==2.1.1', 'gui_scripts', 'deluged')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/deluged", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/lib/python3.11/site-packages/deluge/core/daemon_entry.py", line 15, in <module>
    from deluge.argparserbase import ArgParserBase
  File "/app/lib/python3.11/site-packages/deluge/argparserbase.py", line 16, in <module>
    import deluge.log
  File "/app/lib/python3.11/site-packages/deluge/log.py", line 19, in <module>
    from twisted.internet import defer
  File "/app/lib/python3.11/site-packages/twisted/internet/defer.py", line 44, in <module>
    from twisted.internet.interfaces import IDelayedCall, IReactorTime
  File "/app/lib/python3.11/site-packages/twisted/internet/interfaces.py", line 24, in <module>
    from zope.interface import Attribute, Interface
ModuleNotFoundError: No module named 'zope'
```

**Comment by fastrizwaan** [comment]
https://github.com/flathub/org.deluge_torrent.deluge/pull/19 added zope, but still it is thowing the same error. It took me 4 hours to add those deps manually. but again, zope error :(

we'll raise the issue at deluge

**Comment by fastrizwaan** [comment]
raised the issue https://dev.deluge-torrent.org/ticket/3621#ticket
